### ISSUE TITLE
RFE: inform user when using milestone macro for patches_base

### ISSUE THREAD

**Issue by larsks** [softwarefactory-project/rdopkg#108]
If a spec file contains:

    %global milestone rc2

That "rc2" will be used along with the RPM version to generate the patches_base.  This behavior isn't documented in the man page. Because it is surprising that rdopkg is using information outside of the standard RPM header, rdopkg ought to emit some sort of message when incorporating this additional information.  E.g:

    Found milestone rc2 on line 4, using 2014.2.3rc2 for patches_base

**Comment by yazug** [comment]
@larsks patch merged, address your concern?

**Comment by yac** [comment]
@yazug Only the docs part is merged, this requests `rdopkg` to print/inform that it's using milestone in its mysterious calculations which is a good idea so let's add that.
