### ISSUE TITLE
Migrate rdopkg issues to Software Factory

### ISSUE THREAD

**Issue by apevec** [softwarefactory-project/rdopkg#113]
Software Factory, aka SF ( https://softwarefactory-project.io/docs/ ) is a powerful platform to build software, combining Gerrit, Zuul, Nodepool, Jenkins and StoryBoard, soon DLRN too.

rdopkg could be the framework to combine all client-side CLI for interacting and developing with SF, and first step in integrating it is to move the backlog to the SF's StoryBoard instance: https://softwarefactory-project.io/storyboard/#!/project_group/list

**Comment by yac** [comment]
I'll experiment with storyboard, specifically I'm interested in auto-closing issues on merging patches with appropriate Fixes:

**Comment by ssbarnea** [comment]
I am against this proposal, is like creating a chance for not much benefits. Closing bugs can also be automated here, including more advanced planning.

If it doesn't hurt a lot (most users, not a single one), don't fix it ;)

**Comment by apevec** [comment]
@ssbarnea Gerrit and CI have been migrated to softwarefactory-project.io issues are not migrated for now, but also relying on github vs dogfooding our own tooling is not an ideal end-state

**Comment by yac** [comment]
I've integrated this Issues tracker with SF taiga so this is no longer needed.

**Comment by yazug** [comment]
How does one even go about finding and viewing this storyboard on software-project.io ?? Link? where are issues to be filed/tracked going forward? (want to avoid losses like we had last time this project moved).

**Comment by apevec** [comment]
iirc issues stay here @yazug nothing was lost, SF taiga is used for the unified view of the team's backlog
