### ISSUE TITLE
RFE: .spec linting support

### ISSUE THREAD

**Issue by yac** [softwarefactory-project/rdopkg#115]
In order for `rdopkg` to fix the `.spec` instead of just warning about problem
and failing ([specfile.sanity_check](https://github.com/openstack-packages/rdopkg/blob/master/rdopkg/utils/specfile.py#L340)), more transparent linting mechanism is needed that
allows:

 * checking whether there are `.spec` errors (`rdopkg lint`/`rdopkg check`)
 * fix `.spec` errors (`rdopkg lint --fix`)
 * `rdopkg patch/new-version` integration. Fail on lint warning and tell user to fix with dedicated `rdopkg lint --fix` or additional command option a la `--fix-issues` to avoid touching people's `.spec` files in ways they didn't expect during `patch/new-version`.
 * reusability. Only specific checks might be needed by `patch/new-version` so make it easy to select subset of checks/fixes to perform.
 * easier solution of related issues requesting `.spec` checks: #66, #110, #112, #114

**Comment by yazug** [comment]
I like the idea!

**Comment by bregman-arie** [comment]
It's been a long time since this was opened and we still hit the issue all the time. Do you think we'll a solution soon?
