### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by javierpena** [softwarefactory-project/rdopkg#119]
rdopkg does not support python 3.x, and we will have to make it work sooner or later.

**Comment by yac** [comment]
Second batch of fixes by Javier is under review:
https://review.rdoproject.org/r/#/c/6705/

**Comment by yac** [comment]
rdopkg module now loads under python3 but it's not properly tested.

 python3 tests should be added with tox as requested in #134

**Comment by yac** [comment]
`0.45.0` brings `python3-rdopkg` subpackage as well as improved py3 support including py3 tests which are run on each commit..

While not incredibly tested, `rdopkg` now has Python 3 support.
