### ISSUE TITLE
rdopkg fails to update spec due to "Module rpm is not available"

### ISSUE THREAD

**Issue by bregman-arie** [softwarefactory-project/rdopkg#124]
I ran: "sudo dnf install rpm-python" and this is what I got:

"Last metadata expiration check: 0:19:56 ago on Tue Jul  4 12:52:26 2017.
Package python2-rpm-4.13.0.1-1.fc25.x86_64 is already installed, skipping."

I also tried: "python -c "import rpm" -> NO error

And yet, when I run 'rdopkg patch' I get: "Module rpm is not available. It is required to parse .spec files. Pro tip: `yum install rpm-python`" and the spec remains the same, without any modification.

Operating system: Fedora 25

**Comment by yac** [comment]
How did you install? RPM? pip? master?

What is the output of

    rdopkg --version

and

    rdopkg pkgenv

?

**Comment by bregman-arie** [comment]
RPM.

Version: 0.43
ENV:

# get_package_env
RHOS package detected.
## show_package_env

Package:   openstack-neutron-lbaas
NVR:       1:9.2.0-3
Version:   9.2.0
Upstream:  upstream remote/branch not found
Tag style: X.Y.Z

Patches style:          branch
Dist-git branch:        rhos-10.0-rhel-7
Local patches branch:   rhos-10.0-patches
Remote patches branch:  rhos/rhos-10.0-patches
Remote upstream branch: upstream/master

OS dist:                RHOS
Patches apply method:   autosetup

**Comment by yac** [comment]
This works OK for that particular dist-git on my fedora 24 with both 0.43 and master... weird. Some local python magicks must be in play...

**Comment by bregman-arie** [comment]
k, closing issue. If you'll have an idea in the future as to why it's happening, please ping me.
