### ISSUE TITLE
tests may failing if user has default git hooks installed

### ISSUE THREAD

**Issue by ssbarnea** [softwarefactory-project/rdopkg#128]
If you have any hooks inside `~/.git-template/` you may be surprised to see that `rdopkg` tests are failing. This is happening because during the testing some git repos are checkout and commits are made into them, using the default git settings of the current user.

The workaround for this is to tell git not to use the hooks during testing.

Here is a CR to fix that https://softwarefactory-project.io/r/#/c/8834/

**Comment by yac** [comment]
Fixed in 6a7798ae6e01
