### ISSUE TITLE
avoid macros in changelogs

### ISSUE THREAD

**Issue by ktdreyer** [softwarefactory-project/rdopkg#142]
If a git commit title has a percent "%" character, `rdopkg patch` will write that character directly into the %changelog. RPM interprets this as a macro, and I suspect it causes other tools to choke as well (currently chasing a bug in compose-utils / kobo that may be related).

A simple solution would be to just unilaterally escape all `%` signs before writing the changelog.

**Comment by ktdreyer** [comment]
(the compose-utils bug proved to be [completely unrelated](https://pagure.io/compose-utils/pull-request/59), but we should still avoid writing a single percent sign in the %changelog)

**Comment by yac** [comment]
That's correct, changelog entries sould have `%` escaped.

**Comment by yac** [comment]
Fixed in master.
