### ISSUE TITLE
Normalize commit messages

### ISSUE THREAD

**Issue by yac** [softwarefactory-project/rdopkg#143]
Let's define the best format for commit messages generated by `rdopkg` using feature tests and then make all `rdopkg` actions use it consistently.

I suggest NVR as commit title with changelog list as commit body for all actions that modify Release regardless of # of changelog lines:

    package-name-1.2.3-4
    
    Changelog:
    - This
    - That
    - What Not
    
    Resolves: ...
    Change-Id: ...

Don't forget to also test `rdopkg patch -H <file>`.

`rdopkg update-patches` is special as it doesn't bump NVR.

#140 is related and might be solved as part of this effort.

**Comment by fuzzball81** [comment]
Where would the text be inserted when using the -H option?

**Comment by yac** [comment]
We discussed the best way to handle -H is probably to replace NVR with -H <file> content and append the usual changelog and stuff.

**Comment by yac** [comment]
#121 is also related, make sure `-H` and `--bug` interact nicely.

**Comment by yac** [comment]
Work in Progress: https://softwarefactory-project.io/r/#/c/9781/
