### ISSUE TITLE
RFE: clear messages for missing branches/tags

### ISSUE THREAD

**Issue by yac** [softwarefactory-project/rdopkg#146]
Currently, rdopkg shows a failing git commad as well as its output:

    command failed: git log --format=%h%x1f%s%x1f%b%x1e 11.0.2..patches/rhos-12.0-patches
    stderr:
    fatal: ambiguous argument
    '11.0.2..patches/rhos-12.0-patches': unknown revision or path not in
    the working tree.

but people seem to have problems with deciphering that, so show better error
messages in case of missing **patches branch** or **tag**.

There was a WIP patch on review.rdoproject.org addressing this that got lost
during `rdopkg` migration to SF. It changed overall behavior by strict
checks on existing patches branches/tags and proved to be rather disruptive.

Define rdopkg brancehs/tags expectations/assumptions in feature tests and make
sure `rdopkg` fails gracefully and explains why when branch/tag is missing.

If you encounetered a cryptic rdopkg message, please comment it here so it can
be translated into human language as well.

**Comment by yazug** [comment]
if you have a dist-git branch initialised with srpm from dlrn "rdopkg patch" will blow up as mentioned above until you specify patches_base=<sha1> in the .spec file
