### ISSUE TITLE
rdopkg reqcheck lists packages as MISSING: after adding dependencies with python2-

### ISSUE THREAD

**Issue by karelyatin** [softwarefactory-project/rdopkg#152]
After renaming Requires(python- to python2-) in Spec files, rdopkg reqcheck is showing all packages as MISSING.
 
Reproducing Steps:-
rdopkg clone python-cinderclient
cd python-cinderclient
rdopkg reqcheck

Expected Output:-
Should output correctly the packages which matches, missing, which version's miss match, etc.

Actual Output:-
Despite all packages are synched it shows them as MISSING.

**Comment by apevec** [comment]
I think that should be fixed in https://github.com/openstack/pymod2pkg ?

**Comment by yazug** [comment]
https://github.com/openstack/pymod2pkg/commit/9eb8f76e64601fc3dfc1ddcdb7a67d096a1437b9 - is the change to the default in pymod2pkg which defaults to RDO python-foo instead of python2-foo

**Comment by yac** [comment]
Nothing changes for `python-cinderclient` reproducer even with master `pymod2pkg`.

I need to investigate this further, so far I'd guess `rdopkg` fix will be needed and possibly a update of `python-pymod2pkg` Fedora packages as well, not sure yet.

**Comment by apevec** [comment]
Does not seem to work, with rdopkg-0.46.3-1.fc27.noarch I get for python-networking-generic-switch
( https://review.rdoproject.org/r/12935 )

$ rdopkg reqcheck
MET:
  python-neutron-lib >= 1.13.0  (>= 1.13.0 in .spec)

VERSION MISMATCH:
  python-tenacity >= 4.4.0  (>= 3.2.1 in .spec)

MISSING:
  python-netmiko >= 2.0.2
  openstack-neutron >= 12.0.0
  python-oslo-config >= 5.2.0
  python-oslo-i18n >= 3.15.3
  python-oslo-log >= 3.36.0
  python-six >= 1.10.0
  python-stevedore >= 1.20.0
  python-tooz >= 1.58.0

while actual reqs diff is:
-Requires:       python2-netmiko >= 1.2.5
+Requires:       python2-netmiko >= 2.0.2
-Requires:       python2-oslo-config >= 2:5.1.0
+Requires:       python2-oslo-config >= 2:5.2.0
-Requires:       python-tenacity >= 3.2.1
+Requires:       python-tenacity >= 4.4.0
