### ISSUE TITLE
rdopkg new-version do not entertain short %macros in Name:

### ISSUE THREAD

**Issue by karelyatin** [softwarefactory-project/rdopkg#161]
Detected in:- https://review.rdoproject.org/r/#/c/15777/1 and https://review.rdoproject.org/r/#/c/15772/1

If spec contains macro in Name:,

rdopkg new-version -U -b <tag> will add the macro(without expansion) in the commit message.

For example:-
%global library kuryr-lib
Name: python-%library

rdopkg new-version -U -b 0.8.0 will add following commit message:-

python-%library-0.8.0-1

Changelog: -
     Update to 0.8.0

**Comment by yac** [comment]
So this was just a bad detection of short macros fixed by https://softwarefactory-project.io/r/#/c/14252/ .
