### ISSUE TITLE
Duplication of milestone with milestone-like Release string

### ISSUE THREAD

**Issue by yac** [softwarefactory-project/rdopkg#162]
Details are provided int https://bugzilla.redhat.com/show_bug.cgi?id=1638843

Investigate howto prevent this problem by fixing the parser and/or detecting the problematic case and warning/exiting/correcting it.

**Comment by apevec** [comment]
workaround from linked rhbz:
* remove '%global milestone .0.rc2' line from spec
* fix Release to only contain one %{?milestone}
* remove old '%define upstream_version 9.0.0.0rc3.dev14' line that is overriden few lines bellow and causes confusion
* commit these changes to distgit

After that, rdopkg should work as expected.
