### ISSUE TITLE
[RFE] Add support to report missing BuildRequires in reqcheck

### ISSUE THREAD

**Issue by amoralej** [softwarefactory-project/rdopkg#177]
Currently reqcheck only compares runtime requirements from requirements.txt. It'd be good to also be able to compare BuildRequires from test-requirements.txt and docs/requirements.txt with BuildRequires in the specs.

**Comment by apevec** [comment]
@amoralej duplicate of https://github.com/softwarefactory-project/rdopkg/issues/42 ?

**Comment by amoralej** [comment]
@apevec Yes, looks a doplicate, i'll close it.
