### ISSUE TITLE
[RFE] Allow to provide overrides file to reqcheck

### ISSUE THREAD

**Issue by amoralej** [softwarefactory-project/rdopkg#182]
There are cases when we need to override requirements in two different ways:

- requirements.txt has foo >= 2.0.0 but we want to stay in a lower version for some reason, as having python-foo-1.5.0 in rhel base which "we know" is good enough.
- requirements.txt has bar >= 1.0.0 but we want to totally ignore this dependency as it's not in RDO and it's only required for a very specific feature that is not used/supported by RDO.

In those cases we want rdopkg reqcheck to not report those as failures.

My proposal is to maintain those exceptions as a file in a different repo (not part of rdopkg), an "overrides file" that would contain something like:

override;foo>=1.5.0
ignore;bar

Then we should be able to use something like:

rdopkg reqcheck --overrides overrides-file.txt

**Comment by apevec** [comment]
in current release
