### ISSUE TITLE
Document new version release procedure for developers

### ISSUE THREAD

**Issue by apevec** [softwarefactory-project/rdopkg#44]
Maybe as a section in HACKING.md  ?

**Comment by yac** [comment]
Oh yes, I need to streamline the release process... currently it's done by an ugly script that uses `rdopkg` to package `rdopkg` :)

**Comment by yac** [comment]
I'd publish current release script, but it uses my personal accounts for copr and PyPI so let's do this properly instead and automate rdopkg releases using rpmfactory a la upstream - pushing a version tag should be all human effort required to release new version.

Also, let's build in cbs, not copr.

**Comment by apevec** [comment]
@yac 
CBS would be only for EL7 builds, maybe time to move forward with Fedora pacakge review?

**Comment by yac** [comment]
Automation ftw, let's continue this in #136
