### ISSUE TITLE
rdopkg review-spec fails on rdo-FTBFS reviews

### ISSUE THREAD

**Issue by apevec** [softwarefactory-project/rdopkg#64]
rdopkg review-spec does not handle amending reviews autogenerated  on trunk build failures[1]

```
$ git-review -r review-origin -d 1064
Downloading refs/changes/64/1064/1 from gerrit
Switched to branch "review/rdo_trunk/rdo-FTBFS"
...fix spec...
$ git commit -a --amend
$ rdopkg review-spec
## get_package_env
## review_spec
git review -r review-origin review/rdo_trunk/rdo-FTBFS
The branch 'review/rdo_trunk/rdo-FTBFS' does not exist on the given
remote 'review-origin'. If these changes are intended to start a new
branch, re-run with the '-R' option enabled.
command failed: git review -r review-origin review/rdo_trunk/rdo-FTBFS
```

Branch "review/rdo_trunk/rdo-FTBFS" should not be specified, it is taken from .gitreivew and the git best-practice is to use local topic branches vs submitting from the local mirror of the target branch.

[1] https://review.rdoproject.org/r/#/q/topic:rdo-FTBFS

**Comment by yac** [comment]
This is the command I got from `rpmfactory` folks which doesn't require `.gitreview` at all as discussed in #63
