### ISSUE TITLE
RFC: Integrate 'rpmlint'

### ISSUE THREAD

**Issue by kashyapc** [softwarefactory-project/rdopkg#66]
`rpmlint`[1] is a tool for checking common errors in RPM packages[...] rpmlint can check binary RPMs (files and installed ones), source RPMs[...].

Intergrating `rpmlint` into `rdopkg` allows us to catch any inadvertent mistakes like bogus entries in %changelog or other spec-file mistakes that slip in. This is also useful to those normally not familiar with the RPM ecosystem and tooling around.

Thanks to OpenStack Nova developer Melanie Witt for suggesting the idea on IRC.

[1] https://github.com/rpm-software-management/rpmlint

**Comment by yac** [comment]
Implemented in `0.49.0`.
