### ISSUE TITLE
Integrate `man rdopkg` into RDO website

### ISSUE THREAD

**Issue by yac** [softwarefactory-project/rdopkg#71]
Although I prefer asciidoc which nicely renders to both `man` and HTML, [RDO website](https://github.com/redhat-openstack/website) uses Markdown and it's pretty great to have entire site editable in one git repo.

Let's investigate converting `rdopkg` man pages to a markdown format that can be both consumed by the website and render manpages. asciidoc is a markdown superset, conversion should be simple.

If there is no tooling to allow that, a script/template to convert asciidoc manual to files consumable by website should be created. It could live in `rdopkg`: `make man` creates man pages. `make html` creates HTML man pages. Additionally, `make md` would create Markdown files that could be directly used by [RDO website](). It could also be a separate project or part of [RDO website]() itself.

Finally, https://readthedocs.org/ praises itself for sphinx evangelism and I really hate `_rst_`, so I'm against that. Having the manual integrated into the website is much better.

**Comment by ktdreyer** [comment]
IMHO Asciidoc is superior and we should keep it.

**Comment by pmkovar** [comment]
The RDO website, run by Middleman, can also render AsciiDoc files, so you wouldn't need to convert anything.

See https://www.rdoproject.org/test/ for a demo page.

**Comment by yac** [comment]
https://github.com/softwarefactory-project/rdopkg/blob/master/doc/rdopkg.1.adoc is now rendered nicely but first google search result for `man rdopkg` doesn't show nice rendering of the manual as it should.

**Comment by yac** [comment]
first google result is now a nice rendering of `man rdopkg` by a 3rd party website - done :D
