### ISSUE TITLE
rdopkg patch with dlrn spec files don't bump correctly

### ISSUE THREAD

**Issue by yazug** [softwarefactory-project/rdopkg#77]
when running rdopkg patch on dlrn spec file

The following results which is not valid

-Release: 0.20160817045049.d668fcd%{?dist}
+Release: 0.20160817045050..d668fcd%{?dist}

Personal preference would be something like:

+Release: 0.20160817045049.d668fcd.1%{?dist}

but anything that is valid and doesn't mangle the short sha commit would be preferable

possible bump that would be acceptable:
+Release: 0.20160817045050.d668fcd%{?dist}

**Comment by yac** [comment]
Which `rdopkg` command did you use?

Which distgit is this? I'd like to see whole `.spec`.

**Comment by yazug** [comment]
spec file comes from http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master-tested/python-django-horizon-10.0.0-0.20160817045049.d668fcd.el7.centos.src.rpm

wget <srpm> && rpm2cpio *.src.rpm | cpio -id

and I had a local patches branch that I ran
rdopkg patch

I also get the same results if I do
rdopkg fix

**Comment by yac** [comment]
Currently, `rdopkg` bumps last numeric part of Release and the result with 0.TIMESTAMP.HASH is indeed amusing.

I'll try to figure out a way to detect and support this naming scheme as you suggested - adding `.1` if release ends with hash, otherwise bump latest number.

Supporting all the different conventions out there without magical side-effects is becoming increasingly difficult.

**Comment by yazug** [comment]
https://softwarefactory-project.io/r/9636 is a re-producer for bad behavior

**Comment by yac** [comment]
I have a local path to enable this, but it's conflicting with milestone handling. I need to figure out a clean way to apply correct release bump for different release formats.

**Comment by yac** [comment]
As the hash is not guaranteed to contain letters, the only way I see to tell apart **bump last numeric part** vs suggested **bump last part, add extra .1 if not numeric** is to assume long numbers in release imply the second strategy which is shady at best.

I'd rather use compatible release formats with both RDO CloudSIG and RDO Trunk `.spec`s if possible.

If these formats really must differ, let there be a clear way to detect the non-default one.

**Comment by yac** [comment]
We agreed on `#rdo` meeting that we'll change DLRN Release format from `0.date.hash` to `0.1.date.hash`.

For the old `0.date.hash` format, OSP already uses default rdopkg bumping of last digit. Jon covered this with feature tests, it works expect when hash is numeric only, so this special case needs to be covered.

For the new `0.1.date.hash` format, the second release part should be bumped. This is also the prefered bumping strategy for fedora.
