### ISSUE TITLE
Please add an option to attach builds to bugzilla

### ISSUE THREAD

**Issue by mrunge** [softwarefactory-project/rdopkg#8]
It would be immensely helpful to attach builds directly to bugzilla

E.g. if a changelog line lists a bz number, (in last changelog entry), it should be able to attach the latest build to bz and add a fixed_in_version.

Maybe it's even useful to overwrite fixed_in_version, it there's already one set

**Comment by apevec** [comment]
This is rhbz specific and interfacing with Bugzilla would be out of scope for rdopkg.
