### ISSUE TITLE
rdopkg should support a psychoanalyst option

### ISSUE THREAD

**Issue by booxter** [softwarefactory-project/rdopkg#9]
Every reasonable operating system strives to the point of getting a built-in psychoanalyst feature. F.e. see Emacs [1]. Rdopkg is obviously a lot more than just another tool, and already includes more magic than e.g. OpenBSD, so the analyst feature is essential if we want to see rdopkg running in real, enterprise grade, high available, energy efficient, functional, resilient, and world-class data centers.

The feature could help packagers to control their anger about rdo updates not being pushed into repos in time, or a need to push updates thru bodhi for Fedora that no one actually uses for openstack server side. The analyst would be able to ask reasonable retarded questions about packager mood, and it could also categorize complaints and store them in SQLite database for later extraction (see below).

Once the feature is implemented, we can think of extending it with an option to send complaint report to github, creating an Issue. I'm pissed of that I need to go to github website just to complain about missing feature, so it should be fixed. (Also, where's my analyst to complain to!?)

Issue priority could be adjusted based on the number of exclamation marks or f\* words in the report.

I suggest to use 'rdopkg psycho' for the command.

Kindly yours,
Procrastinator of the Month,
Ihar

1: http://emacswiki.org/emacs/EmacsDoctor

**Comment by hguemar** [comment]
Should be named "doctor" to match M-x doctor in Emacs :wink:

**Comment by paramite** [comment]
:D +1

**Comment by strider** [comment]
:+1:

**Comment by mangelajo** [comment]
+1

rdopkg doctor

**Comment by yac** [comment]
Latest `rdopkg` contains new version of `rdopkg doctor`, now with wisdom and rainbows!

Please reopen this bug if you aren't happy with the current implementation and require deeper psychoanalyst features :)

**Comment by booxter** [comment]
@yac OK. Should I report a separate bug about soundcloud link not working? :-]

**Comment by yac** [comment]
@booxter no more links now, use a newer version :)
